### PR TITLE
Updated completions and added docker-compose completions

### PR DESCRIPTION
**Pull request by rickard-von-essen**
barnybug/docker-fish-completion#11 introduced support for `docker-compose`. This updates the completion with the latest changes and adds docker compose support.

### CODE REVIEW

**Comment by brj** [comment]
@rickard-von-essen Wow, thanks a lot. 

@Markcial You use Docker a lot. Any feedbac?

**Comment by herrbischoff** [comment]
@depressiveRobot: Dunno, I probably overlooked it. Going to check it out.

**Comment by herrbischoff** [comment]
LGTM, merging.

**Comment by rickard-von-essen** [comment]
:+1:

**Comment by Fuco1** [comment]
I might be missing something but where are the docker-compose completions? :O

**Comment by herrbischoff** [comment]
There are no docker-compose completions as docker-compose is a separate application.

Additionally, I have lost interest in Docker, so it would be great if someone else picked up maintaining this plugin.

**Comment by Fuco1** [comment]
@herrbischoff The title of the PR suggests that they were added.  I've opened a PR with some fixes.  This should be pretty low-traffic repo so I might be willing to take over or at least join the project, it shouldn't take much of my time.

**Comment by herrbischoff** [comment]
You're right of course, I missed the name of the PR. I have invited you as a collaborator.

**Comment by Fuco1** [comment]
@herrbischoff Thanks!

**Pull request merged**
